version: '3.8'
services:
  server:
    image: castel-account-book-server
    build:
      context: './apps/server'
      dockerfile: Dockerfile
    ports:
      - '4000:4000'

  web:
    image: castel-account-book-web
    build:
      context: './apps/web'
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
